// Venezuelan states and municipalities data
// Source: https://github.com/marydn/venezuela-sql

export interface Estado {
  id: number;
  nombre: string;
  iso: string;
}

export interface Municipio {
  id: number;
  estadoId: number;
  nombre: string;
}

export const ESTADOS: Estado[] = [
  { id: 1, nombre: 'Amazonas', iso: 'VE-X' },
  { id: 2, nombre: 'Anzoátegui', iso: 'VE-B' },
  { id: 3, nombre: 'Apure', iso: 'VE-C' },
  { id: 4, nombre: 'Aragua', iso: 'VE-D' },
  { id: 5, nombre: 'Barinas', iso: 'VE-E' },
  { id: 6, nombre: 'Bolívar', iso: 'VE-F' },
  { id: 7, nombre: 'Carabobo', iso: 'VE-G' },
  { id: 8, nombre: 'Cojedes', iso: 'VE-H' },
  { id: 9, nombre: 'Delta Amacuro', iso: 'VE-Y' },
  { id: 10, nombre: 'Falcón', iso: 'VE-I' },
  { id: 11, nombre: 'Guárico', iso: 'VE-J' },
  { id: 12, nombre: 'Lara', iso: 'VE-K' },
  { id: 13, nombre: 'Mérida', iso: 'VE-L' },
  { id: 14, nombre: 'Miranda', iso: 'VE-M' },
  { id: 15, nombre: 'Monagas', iso: 'VE-N' },
  { id: 16, nombre: 'Nueva Esparta', iso: 'VE-O' },
  { id: 17, nombre: 'Portuguesa', iso: 'VE-P' },
  { id: 18, nombre: 'Sucre', iso: 'VE-R' },
  { id: 19, nombre: 'Táchira', iso: 'VE-S' },
  { id: 20, nombre: 'Trujillo', iso: 'VE-T' },
  { id: 21, nombre: 'La Guaira', iso: 'VE-W' },
  { id: 22, nombre: 'Yaracuy', iso: 'VE-U' },
  { id: 23, nombre: 'Zulia', iso: 'VE-V' },
  { id: 24, nombre: 'Distrito Capital', iso: 'VE-A' },
  { id: 25, nombre: 'Dependencias Federales', iso: 'VE-Z' },
];

export const MUNICIPIOS: Municipio[] = [
  // Amazonas (1)
  { id: 1, estadoId: 1, nombre: 'Alto Orinoco' },
  { id: 2, estadoId: 1, nombre: 'Atabapo' },
  { id: 3, estadoId: 1, nombre: 'Atures' },
  { id: 4, estadoId: 1, nombre: 'Autana' },
  { id: 5, estadoId: 1, nombre: 'Manapiare' },
  { id: 6, estadoId: 1, nombre: 'Maroa' },
  { id: 7, estadoId: 1, nombre: 'Río Negro' },
  // Anzoátegui (2)
  { id: 8, estadoId: 2, nombre: 'Anaco' },
  { id: 9, estadoId: 2, nombre: 'Aragua' },
  { id: 10, estadoId: 2, nombre: 'Manuel Ezequiel Bruzual' },
  { id: 11, estadoId: 2, nombre: 'Diego Bautista Urbaneja' },
  { id: 12, estadoId: 2, nombre: 'Fernando Peñalver' },
  { id: 13, estadoId: 2, nombre: 'Francisco Del Carmen Carvajal' },
  { id: 14, estadoId: 2, nombre: 'General Sir Arthur McGregor' },
  { id: 15, estadoId: 2, nombre: 'Guanta' },
  { id: 16, estadoId: 2, nombre: 'Independencia' },
  { id: 17, estadoId: 2, nombre: 'José Gregorio Monagas' },
  { id: 18, estadoId: 2, nombre: 'Juan Antonio Sotillo' },
  { id: 19, estadoId: 2, nombre: 'Juan Manuel Cajigal' },
  { id: 20, estadoId: 2, nombre: 'Libertad' },
  { id: 21, estadoId: 2, nombre: 'Francisco de Miranda' },
  { id: 22, estadoId: 2, nombre: 'Pedro María Freites' },
  { id: 23, estadoId: 2, nombre: 'Píritu' },
  { id: 24, estadoId: 2, nombre: 'San José de Guanipa' },
  { id: 25, estadoId: 2, nombre: 'San Juan de Capistrano' },
  { id: 26, estadoId: 2, nombre: 'Santa Ana' },
  { id: 27, estadoId: 2, nombre: 'Simón Bolívar' },
  { id: 28, estadoId: 2, nombre: 'Simón Rodríguez' },
  // Apure (3)
  { id: 29, estadoId: 3, nombre: 'Achaguas' },
  { id: 30, estadoId: 3, nombre: 'Biruaca' },
  { id: 31, estadoId: 3, nombre: 'Muñóz' },
  { id: 32, estadoId: 3, nombre: 'Páez' },
  { id: 33, estadoId: 3, nombre: 'Pedro Camejo' },
  { id: 34, estadoId: 3, nombre: 'Rómulo Gallegos' },
  { id: 35, estadoId: 3, nombre: 'San Fernando' },
  // Aragua (4)
  { id: 36, estadoId: 4, nombre: 'Atanasio Girardot' },
  { id: 37, estadoId: 4, nombre: 'Bolívar' },
  { id: 38, estadoId: 4, nombre: 'Camatagua' },
  { id: 39, estadoId: 4, nombre: 'Francisco Linares Alcántara' },
  { id: 40, estadoId: 4, nombre: 'José Ángel Lamas' },
  { id: 41, estadoId: 4, nombre: 'José Félix Ribas' },
  { id: 42, estadoId: 4, nombre: 'José Rafael Revenga' },
  { id: 43, estadoId: 4, nombre: 'Libertador' },
  { id: 44, estadoId: 4, nombre: 'Mario Briceño Iragorry' },
  { id: 45, estadoId: 4, nombre: 'Ocumare de la Costa de Oro' },
  { id: 46, estadoId: 4, nombre: 'San Casimiro' },
  { id: 47, estadoId: 4, nombre: 'San Sebastián' },
  { id: 48, estadoId: 4, nombre: 'Santiago Mariño' },
  { id: 49, estadoId: 4, nombre: 'Santos Michelena' },
  { id: 50, estadoId: 4, nombre: 'Sucre' },
  { id: 51, estadoId: 4, nombre: 'Tovar' },
  { id: 52, estadoId: 4, nombre: 'Urdaneta' },
  { id: 53, estadoId: 4, nombre: 'Zamora' },
  // Barinas (5)
  { id: 54, estadoId: 5, nombre: 'Alberto Arvelo Torrealba' },
  { id: 55, estadoId: 5, nombre: 'Andrés Eloy Blanco' },
  { id: 56, estadoId: 5, nombre: 'Antonio José de Sucre' },
  { id: 57, estadoId: 5, nombre: 'Arismendi' },
  { id: 58, estadoId: 5, nombre: 'Barinas' },
  { id: 59, estadoId: 5, nombre: 'Bolívar' },
  { id: 60, estadoId: 5, nombre: 'Cruz Paredes' },
  { id: 61, estadoId: 5, nombre: 'Ezequiel Zamora' },
  { id: 62, estadoId: 5, nombre: 'Obispos' },
  { id: 63, estadoId: 5, nombre: 'Pedraza' },
  { id: 64, estadoId: 5, nombre: 'Rojas' },
  { id: 65, estadoId: 5, nombre: 'Sosa' },
  // Bolívar (6)
  { id: 66, estadoId: 6, nombre: 'Caroní' },
  { id: 67, estadoId: 6, nombre: 'Cedeño' },
  { id: 68, estadoId: 6, nombre: 'El Callao' },
  { id: 69, estadoId: 6, nombre: 'Gran Sabana' },
  { id: 70, estadoId: 6, nombre: 'Heres' },
  { id: 71, estadoId: 6, nombre: 'Piar' },
  { id: 72, estadoId: 6, nombre: 'Angostura (Raúl Leoni)' },
  { id: 73, estadoId: 6, nombre: 'Roscio' },
  { id: 74, estadoId: 6, nombre: 'Sifontes' },
  { id: 75, estadoId: 6, nombre: 'Sucre' },
  { id: 76, estadoId: 6, nombre: 'Padre Pedro Chien' },
  // Carabobo (7)
  { id: 77, estadoId: 7, nombre: 'Bejuma' },
  { id: 78, estadoId: 7, nombre: 'Carlos Arvelo' },
  { id: 79, estadoId: 7, nombre: 'Diego Ibarra' },
  { id: 80, estadoId: 7, nombre: 'Guacara' },
  { id: 81, estadoId: 7, nombre: 'Juan José Mora' },
  { id: 82, estadoId: 7, nombre: 'Libertador' },
  { id: 83, estadoId: 7, nombre: 'Los Guayos' },
  { id: 84, estadoId: 7, nombre: 'Miranda' },
  { id: 85, estadoId: 7, nombre: 'Montalbán' },
  { id: 86, estadoId: 7, nombre: 'Naguanagua' },
  { id: 87, estadoId: 7, nombre: 'Puerto Cabello' },
  { id: 88, estadoId: 7, nombre: 'San Diego' },
  { id: 89, estadoId: 7, nombre: 'San Joaquín' },
  { id: 90, estadoId: 7, nombre: 'Valencia' },
  // Cojedes (8)
  { id: 91, estadoId: 8, nombre: 'Anzoátegui' },
  { id: 92, estadoId: 8, nombre: 'Tinaquillo' },
  { id: 93, estadoId: 8, nombre: 'Girardot' },
  { id: 94, estadoId: 8, nombre: 'Lima Blanco' },
  { id: 95, estadoId: 8, nombre: 'Pao de San Juan Bautista' },
  { id: 96, estadoId: 8, nombre: 'Ricaurte' },
  { id: 97, estadoId: 8, nombre: 'Rómulo Gallegos' },
  { id: 98, estadoId: 8, nombre: 'San Carlos' },
  { id: 99, estadoId: 8, nombre: 'Tinaco' },
  // Delta Amacuro (9)
  { id: 100, estadoId: 9, nombre: 'Antonio Díaz' },
  { id: 101, estadoId: 9, nombre: 'Casacoima' },
  { id: 102, estadoId: 9, nombre: 'Pedernales' },
  { id: 103, estadoId: 9, nombre: 'Tucupita' },
  // Falcón (10)
  { id: 104, estadoId: 10, nombre: 'Acosta' },
  { id: 105, estadoId: 10, nombre: 'Bolívar' },
  { id: 106, estadoId: 10, nombre: 'Buchivacoa' },
  { id: 107, estadoId: 10, nombre: 'Cacique Manaure' },
  { id: 108, estadoId: 10, nombre: 'Carirubana' },
  { id: 109, estadoId: 10, nombre: 'Colina' },
  { id: 110, estadoId: 10, nombre: 'Dabajuro' },
  { id: 111, estadoId: 10, nombre: 'Democracia' },
  { id: 112, estadoId: 10, nombre: 'Falcón' },
  { id: 113, estadoId: 10, nombre: 'Federación' },
  { id: 114, estadoId: 10, nombre: 'Jacura' },
  { id: 115, estadoId: 10, nombre: 'José Laurencio Silva' },
  { id: 116, estadoId: 10, nombre: 'Los Taques' },
  { id: 117, estadoId: 10, nombre: 'Mauroa' },
  { id: 118, estadoId: 10, nombre: 'Miranda' },
  { id: 119, estadoId: 10, nombre: 'Monseñor Iturriza' },
  { id: 120, estadoId: 10, nombre: 'Palmasola' },
  { id: 121, estadoId: 10, nombre: 'Petit' },
  { id: 122, estadoId: 10, nombre: 'Píritu' },
  { id: 123, estadoId: 10, nombre: 'San Francisco' },
  { id: 124, estadoId: 10, nombre: 'Sucre' },
  { id: 125, estadoId: 10, nombre: 'Tocópero' },
  { id: 126, estadoId: 10, nombre: 'Unión' },
  { id: 127, estadoId: 10, nombre: 'Urumaco' },
  { id: 128, estadoId: 10, nombre: 'Zamora' },
  // Guárico (11)
  { id: 129, estadoId: 11, nombre: 'Camaguán' },
  { id: 130, estadoId: 11, nombre: 'Chaguaramas' },
  { id: 131, estadoId: 11, nombre: 'El Socorro' },
  { id: 132, estadoId: 11, nombre: 'José Félix Ribas' },
  { id: 133, estadoId: 11, nombre: 'José Tadeo Monagas' },
  { id: 134, estadoId: 11, nombre: 'Juan Germán Roscio' },
  { id: 135, estadoId: 11, nombre: 'Julián Mellado' },
  { id: 136, estadoId: 11, nombre: 'Las Mercedes' },
  { id: 137, estadoId: 11, nombre: 'Leonardo Infante' },
  { id: 138, estadoId: 11, nombre: 'Pedro Zaraza' },
  { id: 139, estadoId: 11, nombre: 'Ortíz' },
  { id: 140, estadoId: 11, nombre: 'San Gerónimo de Guayabal' },
  { id: 141, estadoId: 11, nombre: 'San José de Guaribe' },
  { id: 142, estadoId: 11, nombre: 'Santa María de Ipire' },
  { id: 143, estadoId: 11, nombre: 'Sebastián Francisco de Miranda' },
  // Lara (12)
  { id: 144, estadoId: 12, nombre: 'Andrés Eloy Blanco' },
  { id: 145, estadoId: 12, nombre: 'Crespo' },
  { id: 146, estadoId: 12, nombre: 'Iribarren' },
  { id: 147, estadoId: 12, nombre: 'Jiménez' },
  { id: 148, estadoId: 12, nombre: 'Morán' },
  { id: 149, estadoId: 12, nombre: 'Palavecino' },
  { id: 150, estadoId: 12, nombre: 'Simón Planas' },
  { id: 151, estadoId: 12, nombre: 'Torres' },
  { id: 152, estadoId: 12, nombre: 'Urdaneta' },
  // Mérida (13)
  { id: 179, estadoId: 13, nombre: 'Alberto Adriani' },
  { id: 180, estadoId: 13, nombre: 'Andrés Bello' },
  { id: 181, estadoId: 13, nombre: 'Antonio Pinto Salinas' },
  { id: 182, estadoId: 13, nombre: 'Aricagua' },
  { id: 183, estadoId: 13, nombre: 'Arzobispo Chacón' },
  { id: 184, estadoId: 13, nombre: 'Campo Elías' },
  { id: 185, estadoId: 13, nombre: 'Caracciolo Parra Olmedo' },
  { id: 186, estadoId: 13, nombre: 'Cardenal Quintero' },
  { id: 187, estadoId: 13, nombre: 'Guaraque' },
  { id: 188, estadoId: 13, nombre: 'Julio César Salas' },
  { id: 189, estadoId: 13, nombre: 'Justo Briceño' },
  { id: 190, estadoId: 13, nombre: 'Libertador' },
  { id: 191, estadoId: 13, nombre: 'Miranda' },
  { id: 192, estadoId: 13, nombre: 'Obispo Ramos de Lora' },
  { id: 193, estadoId: 13, nombre: 'Padre Noguera' },
  { id: 194, estadoId: 13, nombre: 'Pueblo Llano' },
  { id: 195, estadoId: 13, nombre: 'Rangel' },
  { id: 196, estadoId: 13, nombre: 'Rivas Dávila' },
  { id: 197, estadoId: 13, nombre: 'Santos Marquina' },
  { id: 198, estadoId: 13, nombre: 'Sucre' },
  { id: 199, estadoId: 13, nombre: 'Tovar' },
  { id: 200, estadoId: 13, nombre: 'Tulio Febres Cordero' },
  { id: 201, estadoId: 13, nombre: 'Zea' },
  // Miranda (14)
  { id: 223, estadoId: 14, nombre: 'Acevedo' },
  { id: 224, estadoId: 14, nombre: 'Andrés Bello' },
  { id: 225, estadoId: 14, nombre: 'Baruta' },
  { id: 226, estadoId: 14, nombre: 'Brión' },
  { id: 227, estadoId: 14, nombre: 'Buroz' },
  { id: 228, estadoId: 14, nombre: 'Carrizal' },
  { id: 229, estadoId: 14, nombre: 'Chacao' },
  { id: 230, estadoId: 14, nombre: 'Cristóbal Rojas' },
  { id: 231, estadoId: 14, nombre: 'El Hatillo' },
  { id: 232, estadoId: 14, nombre: 'Guaicaipuro' },
  { id: 233, estadoId: 14, nombre: 'Independencia' },
  { id: 234, estadoId: 14, nombre: 'Lander' },
  { id: 235, estadoId: 14, nombre: 'Los Salias' },
  { id: 236, estadoId: 14, nombre: 'Páez' },
  { id: 237, estadoId: 14, nombre: 'Paz Castillo' },
  { id: 238, estadoId: 14, nombre: 'Pedro Gual' },
  { id: 239, estadoId: 14, nombre: 'Plaza' },
  { id: 240, estadoId: 14, nombre: 'Simón Bolívar' },
  { id: 241, estadoId: 14, nombre: 'Sucre' },
  { id: 242, estadoId: 14, nombre: 'Urdaneta' },
  { id: 243, estadoId: 14, nombre: 'Zamora' },
  // Monagas (15)
  { id: 258, estadoId: 15, nombre: 'Acosta' },
  { id: 259, estadoId: 15, nombre: 'Aguasay' },
  { id: 260, estadoId: 15, nombre: 'Bolívar' },
  { id: 261, estadoId: 15, nombre: 'Caripe' },
  { id: 262, estadoId: 15, nombre: 'Cedeño' },
  { id: 263, estadoId: 15, nombre: 'Ezequiel Zamora' },
  { id: 264, estadoId: 15, nombre: 'Libertador' },
  { id: 265, estadoId: 15, nombre: 'Maturín' },
  { id: 266, estadoId: 15, nombre: 'Piar' },
  { id: 267, estadoId: 15, nombre: 'Punceres' },
  { id: 268, estadoId: 15, nombre: 'Santa Bárbara' },
  { id: 269, estadoId: 15, nombre: 'Sotillo' },
  { id: 270, estadoId: 15, nombre: 'Uracoa' },
  // Nueva Esparta (16)
  { id: 271, estadoId: 16, nombre: 'Antolín del Campo' },
  { id: 272, estadoId: 16, nombre: 'Arismendi' },
  { id: 273, estadoId: 16, nombre: 'García' },
  { id: 274, estadoId: 16, nombre: 'Gómez' },
  { id: 275, estadoId: 16, nombre: 'Maneiro' },
  { id: 276, estadoId: 16, nombre: 'Marcano' },
  { id: 277, estadoId: 16, nombre: 'Mariño' },
  { id: 278, estadoId: 16, nombre: 'Península de Macanao' },
  { id: 279, estadoId: 16, nombre: 'Tubores' },
  { id: 280, estadoId: 16, nombre: 'Villalba' },
  { id: 281, estadoId: 16, nombre: 'Díaz' },
  // Portuguesa (17)
  { id: 282, estadoId: 17, nombre: 'Agua Blanca' },
  { id: 283, estadoId: 17, nombre: 'Araure' },
  { id: 284, estadoId: 17, nombre: 'Esteller' },
  { id: 285, estadoId: 17, nombre: 'Guanare' },
  { id: 286, estadoId: 17, nombre: 'Guanarito' },
  { id: 287, estadoId: 17, nombre: 'Monseñor José Vicente de Unda' },
  { id: 288, estadoId: 17, nombre: 'Ospino' },
  { id: 289, estadoId: 17, nombre: 'Páez' },
  { id: 290, estadoId: 17, nombre: 'Papelón' },
  { id: 291, estadoId: 17, nombre: 'San Genaro de Boconoíto' },
  { id: 292, estadoId: 17, nombre: 'San Rafael de Onoto' },
  { id: 293, estadoId: 17, nombre: 'Santa Rosalía' },
  { id: 294, estadoId: 17, nombre: 'Sucre' },
  { id: 295, estadoId: 17, nombre: 'Turén' },
  // Sucre (18)
  { id: 296, estadoId: 18, nombre: 'Andrés Eloy Blanco' },
  { id: 297, estadoId: 18, nombre: 'Andrés Mata' },
  { id: 298, estadoId: 18, nombre: 'Arismendi' },
  { id: 299, estadoId: 18, nombre: 'Benítez' },
  { id: 300, estadoId: 18, nombre: 'Bermúdez' },
  { id: 301, estadoId: 18, nombre: 'Bolívar' },
  { id: 302, estadoId: 18, nombre: 'Cajigal' },
  { id: 303, estadoId: 18, nombre: 'Cruz Salmerón Acosta' },
  { id: 304, estadoId: 18, nombre: 'Libertador' },
  { id: 305, estadoId: 18, nombre: 'Mariño' },
  { id: 306, estadoId: 18, nombre: 'Mejía' },
  { id: 307, estadoId: 18, nombre: 'Montes' },
  { id: 308, estadoId: 18, nombre: 'Ribero' },
  { id: 309, estadoId: 18, nombre: 'Sucre' },
  { id: 310, estadoId: 18, nombre: 'Valdéz' },
  // Táchira (19)
  { id: 341, estadoId: 19, nombre: 'Andrés Bello' },
  { id: 342, estadoId: 19, nombre: 'Antonio Rómulo Costa' },
  { id: 343, estadoId: 19, nombre: 'Ayacucho' },
  { id: 344, estadoId: 19, nombre: 'Bolívar' },
  { id: 345, estadoId: 19, nombre: 'Cárdenas' },
  { id: 346, estadoId: 19, nombre: 'Córdoba' },
  { id: 347, estadoId: 19, nombre: 'Fernández Feo' },
  { id: 348, estadoId: 19, nombre: 'Francisco de Miranda' },
  { id: 349, estadoId: 19, nombre: 'García de Hevia' },
  { id: 350, estadoId: 19, nombre: 'Guásimos' },
  { id: 351, estadoId: 19, nombre: 'Independencia' },
  { id: 352, estadoId: 19, nombre: 'Jáuregui' },
  { id: 353, estadoId: 19, nombre: 'José María Vargas' },
  { id: 354, estadoId: 19, nombre: 'Junín' },
  { id: 355, estadoId: 19, nombre: 'Libertad' },
  { id: 356, estadoId: 19, nombre: 'Libertador' },
  { id: 357, estadoId: 19, nombre: 'Lobatera' },
  { id: 358, estadoId: 19, nombre: 'Michelena' },
  { id: 359, estadoId: 19, nombre: 'Panamericano' },
  { id: 360, estadoId: 19, nombre: 'Pedro María Ureña' },
  { id: 361, estadoId: 19, nombre: 'Rafael Urdaneta' },
  { id: 362, estadoId: 19, nombre: 'Samuel Darío Maldonado' },
  { id: 363, estadoId: 19, nombre: 'San Cristóbal' },
  { id: 364, estadoId: 19, nombre: 'Seboruco' },
  { id: 365, estadoId: 19, nombre: 'Simón Rodríguez' },
  { id: 366, estadoId: 19, nombre: 'Sucre' },
  { id: 367, estadoId: 19, nombre: 'Torbes' },
  { id: 368, estadoId: 19, nombre: 'Uribante' },
  { id: 369, estadoId: 19, nombre: 'San Judas Tadeo' },
  // Trujillo (20)
  { id: 370, estadoId: 20, nombre: 'Andrés Bello' },
  { id: 371, estadoId: 20, nombre: 'Boconó' },
  { id: 372, estadoId: 20, nombre: 'Bolívar' },
  { id: 373, estadoId: 20, nombre: 'Candelaria' },
  { id: 374, estadoId: 20, nombre: 'Carache' },
  { id: 375, estadoId: 20, nombre: 'Escuque' },
  { id: 376, estadoId: 20, nombre: 'José Felipe Márquez Cañizalez' },
  { id: 377, estadoId: 20, nombre: 'Juan Vicente Campos Elías' },
  { id: 378, estadoId: 20, nombre: 'La Ceiba' },
  { id: 379, estadoId: 20, nombre: 'Miranda' },
  { id: 380, estadoId: 20, nombre: 'Monte Carmelo' },
  { id: 381, estadoId: 20, nombre: 'Motatán' },
  { id: 382, estadoId: 20, nombre: 'Pampán' },
  { id: 383, estadoId: 20, nombre: 'Pampanito' },
  { id: 384, estadoId: 20, nombre: 'Rafael Rangel' },
  { id: 385, estadoId: 20, nombre: 'San Rafael de Carvajal' },
  { id: 386, estadoId: 20, nombre: 'Sucre' },
  { id: 387, estadoId: 20, nombre: 'Trujillo' },
  { id: 388, estadoId: 20, nombre: 'Urdaneta' },
  { id: 389, estadoId: 20, nombre: 'Valera' },
  // La Guaira (21)
  { id: 390, estadoId: 21, nombre: 'Vargas' },
  // Yaracuy (22)
  { id: 391, estadoId: 22, nombre: 'Arístides Bastidas' },
  { id: 392, estadoId: 22, nombre: 'Bolívar' },
  { id: 407, estadoId: 22, nombre: 'Bruzual' },
  { id: 408, estadoId: 22, nombre: 'Cocorote' },
  { id: 409, estadoId: 22, nombre: 'Independencia' },
  { id: 410, estadoId: 22, nombre: 'José Antonio Páez' },
  { id: 411, estadoId: 22, nombre: 'La Trinidad' },
  { id: 412, estadoId: 22, nombre: 'Manuel Monge' },
  { id: 413, estadoId: 22, nombre: 'Nirgua' },
  { id: 414, estadoId: 22, nombre: 'Peña' },
  { id: 415, estadoId: 22, nombre: 'San Felipe' },
  { id: 416, estadoId: 22, nombre: 'Sucre' },
  { id: 417, estadoId: 22, nombre: 'Urachiche' },
  { id: 418, estadoId: 22, nombre: 'José Joaquín Veroes' },
  // Zulia (23)
  { id: 441, estadoId: 23, nombre: 'Almirante Padilla' },
  { id: 442, estadoId: 23, nombre: 'Baralt' },
  { id: 443, estadoId: 23, nombre: 'Cabimas' },
  { id: 444, estadoId: 23, nombre: 'Catatumbo' },
  { id: 445, estadoId: 23, nombre: 'Colón' },
  { id: 446, estadoId: 23, nombre: 'Francisco Javier Pulgar' },
  { id: 447, estadoId: 23, nombre: 'Páez' },
  { id: 448, estadoId: 23, nombre: 'Jesús Enrique Losada' },
  { id: 449, estadoId: 23, nombre: 'Jesús María Semprún' },
  { id: 450, estadoId: 23, nombre: 'La Cañada de Urdaneta' },
  { id: 451, estadoId: 23, nombre: 'Lagunillas' },
  { id: 452, estadoId: 23, nombre: 'Machiques de Perijá' },
  { id: 453, estadoId: 23, nombre: 'Mara' },
  { id: 454, estadoId: 23, nombre: 'Maracaibo' },
  { id: 455, estadoId: 23, nombre: 'Miranda' },
  { id: 456, estadoId: 23, nombre: 'Rosario de Perijá' },
  { id: 457, estadoId: 23, nombre: 'San Francisco' },
  { id: 458, estadoId: 23, nombre: 'Santa Rita' },
  { id: 459, estadoId: 23, nombre: 'Simón Bolívar' },
  { id: 460, estadoId: 23, nombre: 'Sucre' },
  { id: 461, estadoId: 23, nombre: 'Valmore Rodríguez' },
  // Distrito Capital (24)
  { id: 462, estadoId: 24, nombre: 'Libertador' },
];

// Helper function to get municipalities by state ID
export function getMunicipiosByEstado(estadoId: number): Municipio[] {
  return MUNICIPIOS.filter((m) => m.estadoId === estadoId).sort((a, b) =>
    a.nombre.localeCompare(b.nombre)
  );
}

// Helper function to get state by name
export function getEstadoByNombre(nombre: string): Estado | undefined {
  return ESTADOS.find((e) => e.nombre === nombre);
}

// Helper function to get municipality by name and state
export function getMunicipioByNombre(
  nombre: string,
  estadoId: number
): Municipio | undefined {
  return MUNICIPIOS.find((m) => m.estadoId === estadoId && m.nombre === nombre);
}

// Get sorted states for select options
export function getEstadosOptions(): { value: string; label: string }[] {
  return [
    { value: '', label: 'Selecciona un estado' },
    ...ESTADOS.sort((a, b) => a.nombre.localeCompare(b.nombre)).map((e) => ({
      value: e.nombre,
      label: e.nombre,
    })),
  ];
}

// Get municipalities options for a given state name
export function getMunicipiosOptions(
  estadoNombre: string
): { value: string; label: string }[] {
  const estado = getEstadoByNombre(estadoNombre);
  if (!estado) {
    return [{ value: '', label: 'Primero selecciona un estado' }];
  }

  const municipios = getMunicipiosByEstado(estado.id);
  return [
    { value: '', label: 'Selecciona un municipio' },
    ...municipios.map((m) => ({
      value: m.nombre,
      label: m.nombre,
    })),
  ];
}
